### PR TITLE
Setup/docker v1

### LINKED ISSUE #9: Please use docker for the project
**Is your feature request related to a problem? Please describe.**
4 persons working on the project, with different env. Many dependencies problems

**Describe the solution you'd like**
Docker will solve that

**Describe alternatives you've considered**
Staying as it is, but docker is better

**Additional context**
I love whales and docks

### PR DESCRIPTION
**Pull request by H-L**
#### :tophat: What? Why?
Setting up first version of Docker build (development only)

#### :pushpin: Related Issues
- Fixes #9 

#### :clipboard: Subtasks
- [x] Fix error on eslint-rails command
- [x] Fix error on Ruby version (let's use the 2.6.2 !)
- [ ] Fix error on db build CI (cf. image below)

### :camera: Screenshots (optional)
Actual error on build

### CODE REVIEW

**Comment by H-L** [comment]
Yup. I'll work on it till it works (but not as late as yesterday).

**Comment by H-L** [comment]
I have no idea what the error really means tho 🤔
Kind of weird it did not work since it passes for master.

**Comment by H-L** [comment]
I installed CircleCI locally, sorry for the noise. I'll it all and come back with a working PR ;)

**Comment by armandfardeau** [comment]
@H-L Actually I already make these changes on my branch. We will merge this and work on conflicts.

**Pull request merged**
